name = "Transformers"
uuid = "840acacd-4141-472b-bd7c-0acec9b507ea"
authors = ["Jules Merckx"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
